[project]
name = "dmml_project"
version = "0.1.0"
dependencies = [
    "scikit-learn",
    "pandas",
    "numpy",
    "matplotlib",
    "nltk",
    "tqdm",
    "seaborn",
    "torch",
]
[tool.setuptools]
package-dir = {"dmml_project" = "src"}